services:
  - type: web
    name: beataddicts-pro
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: STRIPE_SECRET
        value: sk_live_...
      - key: PLATINUM_PRICE_ID
        value: price_...
